apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: dotnet-runtime:3.0
        namespace: {{ .Values.namespace }}
    type: Source
  triggers: []