apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dotnet-build
  namespace: {{ .Values.namespace }}
spec:
  inputs:
    resources:
    - name: source
      type: git
  steps:    
    - name: publish
      image: {{ .Values.buildImage }}
      workingDir: /workspace/source/app
      command: ["dotnet"]
      args:
        - "publish"
        - "-c"
        - "Release"
        - "/p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App"
    - name: build-image
      image: {{ .Values.cliImage }}
      workingDir: /workspace/source/app
      command: ["/usr/bin/oc"]
      args:
        - "start-build"
        - {{ .Values.name }}
        - "--from-dir=bin/Release/netcoreapp3.1/publish"
        - "--follow"