apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dotnet-build
  namespace: {{ .Values.namespace }}
spec:
  inputs:
    resources:
    - name: source
      type: git
  steps:    
    - name: publish
      {{ if .Values.useInternalRegistry }}
      image: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/dotnet:3.1
      {{ else }}
      image: registry.access.redhat.com/ubi8/dotnet-31:3.1
      {{ end }}
      workingDir: /workspace/source/app
      command: ["dotnet"]
      args:
        - "publish"
        - "-c"
        - "Release"
        - "/p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App"
    - name: build-image
      {{ if .Values.useInternalRegistry }}
      image: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/origin-cli:latest
      {{ else }}
      image: quay.io/openshift/origin-cli:latest
      {{ end }}
      workingDir: /workspace/source/app
      command: ["/usr/bin/oc"]
      args:
        - "start-build"
        - {{ .Values.name }}
        - "--from-dir=bin/Release/netcoreapp3.1/publish"
        - "--follow"