apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dotnet-ex
spec:
  output:
    to:
      kind: ImageStreamTag
      name: dotnet-ex:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: dotnet-runtime:3.0
        namespace: openshift
    type: Source
  triggers: []