apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  output:
{{ if .Values.useInternalRegistry == 'true' }}
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
{{ else }}
    to:
      kind: DockerImage
      name: {{ .Values.externalOutputImage }}
    pushSecret:
      name: {{ .Values.pushSecretName }}
{{ end }}
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: dotnet-runtime:3.1
        namespace: {{ .Values.namespace }}
    type: Source
  triggers: []