apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pipelines
  namespace: {{ .Values.namespace }}
spec:
  type: git
  params:
  - name: url
    value: {{ .Values.gitRepo }}
  - name: revision
    value: {{ .Values.gitBranch }}
  - name: sslVerify
    value: '{{ .Values.gitSslVerify }}'