apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dotnet-ex
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: origin-cli
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: quay.io/openshift/origin-cli:latest
    importPolicy:
      scheduled: true
    name: "latest"
    referencePolicy:
      type: Local