apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    deploymentConfig: {{ .Values.name }}